name: 'snowplow_custom_example'
version: '0.13.3'
config-version: 2


profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

vars:
  snowplow__sessions_table: "{{ ref('snowplow_web_sessions_custom') }}" # Redirect references to sessions table to your custom version.

models:
  snowplow_custom_example:
    snowplow_web_custom_modules:
      +tags: snowplow_web_incremental #Adds tag to all models in the 'snowplow_web_custom_modules' directory
  snowplow_web: # Only applies to models provided by the Snowplow Web dbt package
    sessions:
      snowplow_web_sessions:
        +enabled: false # Disable the snowplow_web_sessions model as we have our custom version, snowplow_web_sessions_custom
