name: 'fueled_custom_example'
version: '0.14.1'
config-version: 2

dispatch:
  - macro_namespace: dbt
    search_order: ['fueled_utils', 'dbt']

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

vars:
  fueled__sessions_table: "{{ ref('fueled_web_sessions_custom') }}" # Redirect references to sessions table to your custom version.

models:
  fueled_custom_example:
    fueled_web_custom_modules:
      +tags: fueled_web_incremental #Adds tag to all models in the 'fueled_web_custom_modules' directory
  fueled_web: # Only applies to models provided by the Fueled Web dbt package
    sessions:
      fueled_web_sessions:
        +enabled: false # Disable the fueled_web_sessions model as we have our custom version, fueled_web_sessions_custom
